version: '3.8'

services:
  web:
    build: ./
    ports:
      - 8004:8000
    command: poetry run start
    volumes:
      - ./:/usr/src/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=monkey_user
      - POSTGRES_PASSWORD=monkey_pass
      - POSTGRES_DB=monkey_db
      - POSTGRES_SERVER=pgbouncer
      - POSTGRES_PORT=6432
    depends_on:
      - pgbouncer
    sysctls:
      - net.ipv4.tcp_keepalive_time=200

  worker:
    build: ./
    command: poetry run celery -A ipr.app.celery worker -P threads -E --concurrency=30 --loglevel=info
    volumes:
      - ./:/usr/src/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=monkey_user
      - POSTGRES_PASSWORD=monkey_pass
      - POSTGRES_DB=monkey_db
      - POSTGRES_SERVER=pgbouncer
      - POSTGRES_PORT=6432
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./
    command: poetry run celery -A ipr.app.celery flower
    volumes:
      - ./:/usr/src/app
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=monkey_user
      - POSTGRES_PASSWORD=monkey_pass
      - POSTGRES_DB=monkey_db
      - POSTGRES_SERVER=pgbouncer
      - POSTGRES_PORT=6432
    depends_on:
      - redis
      - web
      - worker
      - pgbouncer

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=monkey_user
      - POSTGRES_PASSWORD=monkey_pass
      - POSTGRES_DB=monkey_db
    expose:
      - 5432
    sysctls:
      - net.ipv4.tcp_keepalive_time=200

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=monkey_user
      - POSTGRESQL_PASSWORD=monkey_pass
      - POSTGRESQL_DATABASE=monkey_db
      - PGBOUNCER_DATABASE=monkey_db
      - PGBOUNCER_MAX_CLIENT_CONN=10000
      - PGBOUNCER_QUERY_WAIT_TIMEOUT=5
    depends_on:
      - db
    sysctls:
      - net.ipv4.tcp_keepalive_time=200

volumes:
  postgres_data:
