"""init

Revision ID: 3f27a8c6fc94
Revises: 
Create Date: 2022-05-09 22:23:55.262821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f27a8c6fc94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('PROJECT_CREATED', 'CLONE_START', 'CLONE_END', 'REUSE_START', 'REUSE_END', 'SCANCODE_START', 'SCANCODE_END', 'BLOCKCHAIN_START', 'BLOCKCHAIN_END', name='state', native_enum=False), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_url'), 'audit_logs', ['url'], unique=False)
    op.create_table('projects',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('reuse_compliant', sa.Boolean(), nullable=True),
    sa.Column('reuse_report', sa.String(), nullable=True),
    sa.Column('scancode_report', sa.String(), nullable=True),
    sa.Column('sawroom_tag', sa.String(), nullable=True),
    sa.Column('fabric_tag', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_fabric_tag'), 'projects', ['fabric_tag'], unique=False)
    op.create_index(op.f('ix_projects_sawroom_tag'), 'projects', ['sawroom_tag'], unique=False)
    op.create_index(op.f('ix_projects_url'), 'projects', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_url'), table_name='projects')
    op.drop_index(op.f('ix_projects_sawroom_tag'), table_name='projects')
    op.drop_index(op.f('ix_projects_fabric_tag'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_url'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
